spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://my-rds.cgxtdz3dn3oc.ap-northeast-2.rds.amazonaws.com:3306/init
    username: pcy
    password: qwer1234!

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .mustache


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

# 스프링버전 mustache 한글 깨짐 이슈
server:
  servlet:
    encoding:
      force-response: true