spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://my-rds.cgxtdz3dn3oc.ap-northeast-2.rds.amazonaws.com:3306/init
    username: pcy
    password: qwer1234!

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
